# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.transaction_api_option_deliverable import TransactionAPIOptionDeliverable

class TestTransactionAPIOptionDeliverable(unittest.TestCase):
    """TransactionAPIOptionDeliverable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionAPIOptionDeliverable:
        """Test TransactionAPIOptionDeliverable
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionAPIOptionDeliverable`
        """
        model = TransactionAPIOptionDeliverable()
        if include_optional:
            return TransactionAPIOptionDeliverable(
                root_symbol = '',
                strike_percent = 56,
                deliverable_number = 56,
                deliverable_units = 1.337,
                deliverable = None,
                asset_type = 'EQUITY'
            )
        else:
            return TransactionAPIOptionDeliverable(
        )
        """

    def testTransactionAPIOptionDeliverable(self):
        """Test TransactionAPIOptionDeliverable"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
