# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.order_activity import OrderActivity

class TestOrderActivity(unittest.TestCase):
    """OrderActivity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderActivity:
        """Test OrderActivity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderActivity`
        """
        model = OrderActivity()
        if include_optional:
            return OrderActivity(
                activity_type = 'EXECUTION',
                execution_type = 'FILL',
                quantity = 1.337,
                order_remaining_quantity = 1.337,
                execution_legs = [
                    openapi_client.models.execution_leg.ExecutionLeg(
                        leg_id = 56, 
                        price = 1.337, 
                        quantity = 1.337, 
                        mismarked_quantity = 1.337, 
                        instrument_id = 56, 
                        time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return OrderActivity(
        )
        """

    def testOrderActivity(self):
        """Test OrderActivity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
