# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.order_strategy_type import OrderStrategyType

class TestOrderStrategyType(unittest.TestCase):
    """OrderStrategyType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderStrategyType(self):
        """Test OrderStrategyType"""
        # inst = OrderStrategyType()

if __name__ == '__main__':
    unittest.main()
