# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.orders_api import OrdersApi


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrdersApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_order(self) -> None:
        """Test case for cancel_order

        Cancel an order for a specific account
        """
        pass

    def test_get_order(self) -> None:
        """Test case for get_order

        Get a specific order by its ID, for a specific account
        """
        pass

    def test_get_orders_by_path_param(self) -> None:
        """Test case for get_orders_by_path_param

        Get all orders for a specific account.
        """
        pass

    def test_get_orders_by_query_param(self) -> None:
        """Test case for get_orders_by_query_param

        Get all orders for all accounts
        """
        pass

    def test_place_order(self) -> None:
        """Test case for place_order

        Place order for a specific account.
        """
        pass

    def test_preview_order(self) -> None:
        """Test case for preview_order

        Preview order for a specific account. **Coming Soon**.
        """
        pass

    def test_replace_order(self) -> None:
        """Test case for replace_order

        Replace order for a specific account
        """
        pass


if __name__ == '__main__':
    unittest.main()
