# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.user_preference_api import UserPreferenceApi


class TestUserPreferenceApi(unittest.TestCase):
    """UserPreferenceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserPreferenceApi()

    def tearDown(self) -> None:
        pass

    def test_get_user_preference(self) -> None:
        """Test case for get_user_preference

        Get user preference information for the logged in user.
        """
        pass


if __name__ == '__main__':
    unittest.main()
