# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.order_leg_collection import OrderLegCollection

class TestOrderLegCollection(unittest.TestCase):
    """OrderLegCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderLegCollection:
        """Test OrderLegCollection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderLegCollection`
        """
        model = OrderLegCollection()
        if include_optional:
            return OrderLegCollection(
                order_leg_type = 'EQUITY',
                leg_id = 56,
                instrument = None,
                instruction = 'BUY',
                position_effect = 'OPENING',
                quantity = 1.337,
                quantity_type = 'ALL_SHARES',
                div_cap_gains = 'REINVEST',
                to_symbol = ''
            )
        else:
            return OrderLegCollection(
        )
        """

    def testOrderLegCollection(self):
        """Test OrderLegCollection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
