# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.execution_leg import ExecutionLeg

class TestExecutionLeg(unittest.TestCase):
    """ExecutionLeg unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExecutionLeg:
        """Test ExecutionLeg
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExecutionLeg`
        """
        model = ExecutionLeg()
        if include_optional:
            return ExecutionLeg(
                leg_id = 56,
                price = 1.337,
                quantity = 1.337,
                mismarked_quantity = 1.337,
                instrument_id = 56,
                time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ExecutionLeg(
        )
        """

    def testExecutionLeg(self):
        """Test ExecutionLeg"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
