# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.accounts_api import AccountsApi


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountsApi()

    def tearDown(self) -> None:
        pass

    def test_get_account(self) -> None:
        """Test case for get_account

        Get a specific account balance and positions for the logged in user.
        """
        pass

    def test_get_account_numbers(self) -> None:
        """Test case for get_account_numbers

        Get list of account numbers and their encrypted values
        """
        pass

    def test_get_accounts(self) -> None:
        """Test case for get_accounts

        Get linked account(s) balances and positions for the logged in user.
        """
        pass


if __name__ == '__main__':
    unittest.main()
