# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.cash_balance import CashBalance

class TestCashBalance(unittest.TestCase):
    """CashBalance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CashBalance:
        """Test CashBalance
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CashBalance`
        """
        model = CashBalance()
        if include_optional:
            return CashBalance(
                cash_available_for_trading = 1.337,
                cash_available_for_withdrawal = 1.337,
                cash_call = 1.337,
                long_non_marginable_market_value = 1.337,
                total_cash = 1.337,
                cash_debit_call_value = 1.337,
                unsettled_cash = 1.337
            )
        else:
            return CashBalance(
        )
        """

    def testCashBalance(self):
        """Test CashBalance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
