# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.collective_investment import CollectiveInvestment

class TestCollectiveInvestment(unittest.TestCase):
    """CollectiveInvestment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CollectiveInvestment:
        """Test CollectiveInvestment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CollectiveInvestment`
        """
        model = CollectiveInvestment()
        if include_optional:
            return CollectiveInvestment(
                type = 'UNIT_INVESTMENT_TRUST',
                asset_type = 'EQUITY',
                cusip = '',
                symbol = '',
                description = '',
                instrument_id = 56,
                net_change = 1.337
            )
        else:
            return CollectiveInvestment(
                asset_type = 'EQUITY',
        )
        """

    def testCollectiveInvestment(self):
        """Test CollectiveInvestment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
