# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.commission_and_fee import CommissionAndFee

class TestCommissionAndFee(unittest.TestCase):
    """CommissionAndFee unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommissionAndFee:
        """Test CommissionAndFee
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommissionAndFee`
        """
        model = CommissionAndFee()
        if include_optional:
            return CommissionAndFee(
                commission = openapi_client.models.commission.Commission(
                    commission_legs = [
                        openapi_client.models.commission_leg.CommissionLeg(
                            commission_values = [
                                openapi_client.models.commission_value.CommissionValue(
                                    value = 1.337, 
                                    type = 'COMMISSION', )
                                ], )
                        ], ),
                fee = openapi_client.models.fees.Fees(
                    fee_legs = [
                        openapi_client.models.fee_leg.FeeLeg(
                            fee_values = [
                                openapi_client.models.fee_value.FeeValue(
                                    value = 1.337, 
                                    type = 'COMMISSION', )
                                ], )
                        ], ),
                true_commission = openapi_client.models.commission.Commission(
                    commission_legs = [
                        openapi_client.models.commission_leg.CommissionLeg(
                            commission_values = [
                                openapi_client.models.commission_value.CommissionValue(
                                    value = 1.337, 
                                    type = 'COMMISSION', )
                                ], )
                        ], )
            )
        else:
            return CommissionAndFee(
        )
        """

    def testCommissionAndFee(self):
        """Test CommissionAndFee"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
