# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.price_link_type import PriceLinkType

class TestPriceLinkType(unittest.TestCase):
    """PriceLinkType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPriceLinkType(self):
        """Test PriceLinkType"""
        # inst = PriceLinkType()

if __name__ == '__main__':
    unittest.main()
