# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.account_number_hash import AccountNumberHash

class TestAccountNumberHash(unittest.TestCase):
    """AccountNumberHash unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountNumberHash:
        """Test AccountNumberHash
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountNumberHash`
        """
        model = AccountNumberHash()
        if include_optional:
            return AccountNumberHash(
                account_number = '',
                hash_value = ''
            )
        else:
            return AccountNumberHash(
        )
        """

    def testAccountNumberHash(self):
        """Test AccountNumberHash"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
