# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.order_leg import OrderLeg

class TestOrderLeg(unittest.TestCase):
    """OrderLeg unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderLeg:
        """Test OrderLeg
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderLeg`
        """
        model = OrderLeg()
        if include_optional:
            return OrderLeg(
                ask_price = 1.337,
                bid_price = 1.337,
                last_price = 1.337,
                mark_price = 1.337,
                projected_commission = 1.337,
                quantity = 1.337,
                final_symbol = '',
                leg_id = 1.337,
                asset_type = 'EQUITY',
                instruction = 'BUY'
            )
        else:
            return OrderLeg(
        )
        """

    def testOrderLeg(self):
        """Test OrderLeg"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
