# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class CashBalance(BaseModel):
    """
    CashBalance
    """ # noqa: E501
    cash_available_for_trading: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="cashAvailableForTrading")
    cash_available_for_withdrawal: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="cashAvailableForWithdrawal")
    cash_call: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="cashCall")
    long_non_marginable_market_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="longNonMarginableMarketValue")
    total_cash: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="totalCash")
    cash_debit_call_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="cashDebitCallValue")
    unsettled_cash: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="unsettledCash")
    __properties: ClassVar[List[str]] = ["cashAvailableForTrading", "cashAvailableForWithdrawal", "cashCall", "longNonMarginableMarketValue", "totalCash", "cashDebitCallValue", "unsettledCash"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CashBalance from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CashBalance from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cashAvailableForTrading": obj.get("cashAvailableForTrading"),
            "cashAvailableForWithdrawal": obj.get("cashAvailableForWithdrawal"),
            "cashCall": obj.get("cashCall"),
            "longNonMarginableMarketValue": obj.get("longNonMarginableMarketValue"),
            "totalCash": obj.get("totalCash"),
            "cashDebitCallValue": obj.get("cashDebitCallValue"),
            "unsettledCash": obj.get("unsettledCash")
        })
        return _obj


