# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FeeType(str, Enum):
    """
    FeeType
    """

    """
    allowed enum values
    """
    COMMISSION = 'COMMISSION'
    SEC_FEE = 'SEC_FEE'
    STR_FEE = 'STR_FEE'
    R_FEE = 'R_FEE'
    CDSC_FEE = 'CDSC_FEE'
    OPT_REG_FEE = 'OPT_REG_FEE'
    ADDITIONAL_FEE = 'ADDITIONAL_FEE'
    MISCELLANEOUS_FEE = 'MISCELLANEOUS_FEE'
    FTT = 'FTT'
    FUTURES_CLEARING_FEE = 'FUTURES_CLEARING_FEE'
    FUTURES_DESK_OFFICE_FEE = 'FUTURES_DESK_OFFICE_FEE'
    FUTURES_EXCHANGE_FEE = 'FUTURES_EXCHANGE_FEE'
    FUTURES_GLOBEX_FEE = 'FUTURES_GLOBEX_FEE'
    FUTURES_NFA_FEE = 'FUTURES_NFA_FEE'
    FUTURES_PIT_BROKERAGE_FEE = 'FUTURES_PIT_BROKERAGE_FEE'
    FUTURES_TRANSACTION_FEE = 'FUTURES_TRANSACTION_FEE'
    LOW_PROCEEDS_COMMISSION = 'LOW_PROCEEDS_COMMISSION'
    BASE_CHARGE = 'BASE_CHARGE'
    GENERAL_CHARGE = 'GENERAL_CHARGE'
    GST_FEE = 'GST_FEE'
    TAF_FEE = 'TAF_FEE'
    INDEX_OPTION_FEE = 'INDEX_OPTION_FEE'
    TEFRA_TAX = 'TEFRA_TAX'
    STATE_TAX = 'STATE_TAX'
    UNKNOWN = 'UNKNOWN'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FeeType from a JSON string"""
        return cls(json.loads(json_str))


