# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.margin_balance import MarginBalance
from openapi_client.models.margin_initial_balance import MarginInitialBalance
from openapi_client.models.position import Position
from openapi_client.models.securities_account_base import SecuritiesAccountBase
from typing import Optional, Set
from typing_extensions import Self

class MarginAccount(SecuritiesAccountBase):
    """
    MarginAccount
    """ # noqa: E501
    initial_balances: Optional[MarginInitialBalance] = Field(default=None, alias="initialBalances")
    current_balances: Optional[MarginBalance] = Field(default=None, alias="currentBalances")
    projected_balances: Optional[MarginBalance] = Field(default=None, alias="projectedBalances")
    __properties: ClassVar[List[str]] = ["type", "accountNumber", "roundTrips", "isDayTrader", "isClosingOnlyRestricted", "pfcbFlag", "positions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MarginAccount from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in positions (list)
        _items = []
        if self.positions:
            for _item_positions in self.positions:
                if _item_positions:
                    _items.append(_item_positions.to_dict())
            _dict['positions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MarginAccount from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "accountNumber": obj.get("accountNumber"),
            "roundTrips": obj.get("roundTrips"),
            "isDayTrader": obj.get("isDayTrader") if obj.get("isDayTrader") is not None else False,
            "isClosingOnlyRestricted": obj.get("isClosingOnlyRestricted") if obj.get("isClosingOnlyRestricted") is not None else False,
            "pfcbFlag": obj.get("pfcbFlag") if obj.get("pfcbFlag") is not None else False,
            "positions": [Position.from_dict(_item) for _item in obj["positions"]] if obj.get("positions") is not None else None
        })
        return _obj


