# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class MarginBalance(BaseModel):
    """
    MarginBalance
    """ # noqa: E501
    available_funds: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="availableFunds")
    available_funds_non_marginable_trade: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="availableFundsNonMarginableTrade")
    buying_power: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="buyingPower")
    buying_power_non_marginable_trade: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="buyingPowerNonMarginableTrade")
    day_trading_buying_power: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="dayTradingBuyingPower")
    day_trading_buying_power_call: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="dayTradingBuyingPowerCall")
    equity: Optional[Union[StrictFloat, StrictInt]] = None
    equity_percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="equityPercentage")
    long_margin_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="longMarginValue")
    maintenance_call: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="maintenanceCall")
    maintenance_requirement: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="maintenanceRequirement")
    margin_balance: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="marginBalance")
    reg_t_call: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="regTCall")
    short_balance: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="shortBalance")
    short_margin_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="shortMarginValue")
    sma: Optional[Union[StrictFloat, StrictInt]] = None
    is_in_call: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="isInCall")
    stock_buying_power: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="stockBuyingPower")
    option_buying_power: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="optionBuyingPower")
    __properties: ClassVar[List[str]] = ["availableFunds", "availableFundsNonMarginableTrade", "buyingPower", "buyingPowerNonMarginableTrade", "dayTradingBuyingPower", "dayTradingBuyingPowerCall", "equity", "equityPercentage", "longMarginValue", "maintenanceCall", "maintenanceRequirement", "marginBalance", "regTCall", "shortBalance", "shortMarginValue", "sma", "isInCall", "stockBuyingPower", "optionBuyingPower"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MarginBalance from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MarginBalance from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "availableFunds": obj.get("availableFunds"),
            "availableFundsNonMarginableTrade": obj.get("availableFundsNonMarginableTrade"),
            "buyingPower": obj.get("buyingPower"),
            "buyingPowerNonMarginableTrade": obj.get("buyingPowerNonMarginableTrade"),
            "dayTradingBuyingPower": obj.get("dayTradingBuyingPower"),
            "dayTradingBuyingPowerCall": obj.get("dayTradingBuyingPowerCall"),
            "equity": obj.get("equity"),
            "equityPercentage": obj.get("equityPercentage"),
            "longMarginValue": obj.get("longMarginValue"),
            "maintenanceCall": obj.get("maintenanceCall"),
            "maintenanceRequirement": obj.get("maintenanceRequirement"),
            "marginBalance": obj.get("marginBalance"),
            "regTCall": obj.get("regTCall"),
            "shortBalance": obj.get("shortBalance"),
            "shortMarginValue": obj.get("shortMarginValue"),
            "sma": obj.get("sma"),
            "isInCall": obj.get("isInCall"),
            "stockBuyingPower": obj.get("stockBuyingPower"),
            "optionBuyingPower": obj.get("optionBuyingPower")
        })
        return _obj


