# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class MarginInitialBalance(BaseModel):
    """
    MarginInitialBalance
    """ # noqa: E501
    accrued_interest: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="accruedInterest")
    available_funds_non_marginable_trade: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="availableFundsNonMarginableTrade")
    bond_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="bondValue")
    buying_power: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="buyingPower")
    cash_balance: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="cashBalance")
    cash_available_for_trading: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="cashAvailableForTrading")
    cash_receipts: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="cashReceipts")
    day_trading_buying_power: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="dayTradingBuyingPower")
    day_trading_buying_power_call: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="dayTradingBuyingPowerCall")
    day_trading_equity_call: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="dayTradingEquityCall")
    equity: Optional[Union[StrictFloat, StrictInt]] = None
    equity_percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="equityPercentage")
    liquidation_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="liquidationValue")
    long_margin_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="longMarginValue")
    long_option_market_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="longOptionMarketValue")
    long_stock_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="longStockValue")
    maintenance_call: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="maintenanceCall")
    maintenance_requirement: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="maintenanceRequirement")
    margin: Optional[Union[StrictFloat, StrictInt]] = None
    margin_equity: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="marginEquity")
    money_market_fund: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="moneyMarketFund")
    mutual_fund_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="mutualFundValue")
    reg_t_call: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="regTCall")
    short_margin_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="shortMarginValue")
    short_option_market_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="shortOptionMarketValue")
    short_stock_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="shortStockValue")
    total_cash: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="totalCash")
    is_in_call: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="isInCall")
    unsettled_cash: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="unsettledCash")
    pending_deposits: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="pendingDeposits")
    margin_balance: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="marginBalance")
    short_balance: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="shortBalance")
    account_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="accountValue")
    __properties: ClassVar[List[str]] = ["accruedInterest", "availableFundsNonMarginableTrade", "bondValue", "buyingPower", "cashBalance", "cashAvailableForTrading", "cashReceipts", "dayTradingBuyingPower", "dayTradingBuyingPowerCall", "dayTradingEquityCall", "equity", "equityPercentage", "liquidationValue", "longMarginValue", "longOptionMarketValue", "longStockValue", "maintenanceCall", "maintenanceRequirement", "margin", "marginEquity", "moneyMarketFund", "mutualFundValue", "regTCall", "shortMarginValue", "shortOptionMarketValue", "shortStockValue", "totalCash", "isInCall", "unsettledCash", "pendingDeposits", "marginBalance", "shortBalance", "accountValue"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MarginInitialBalance from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MarginInitialBalance from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accruedInterest": obj.get("accruedInterest"),
            "availableFundsNonMarginableTrade": obj.get("availableFundsNonMarginableTrade"),
            "bondValue": obj.get("bondValue"),
            "buyingPower": obj.get("buyingPower"),
            "cashBalance": obj.get("cashBalance"),
            "cashAvailableForTrading": obj.get("cashAvailableForTrading"),
            "cashReceipts": obj.get("cashReceipts"),
            "dayTradingBuyingPower": obj.get("dayTradingBuyingPower"),
            "dayTradingBuyingPowerCall": obj.get("dayTradingBuyingPowerCall"),
            "dayTradingEquityCall": obj.get("dayTradingEquityCall"),
            "equity": obj.get("equity"),
            "equityPercentage": obj.get("equityPercentage"),
            "liquidationValue": obj.get("liquidationValue"),
            "longMarginValue": obj.get("longMarginValue"),
            "longOptionMarketValue": obj.get("longOptionMarketValue"),
            "longStockValue": obj.get("longStockValue"),
            "maintenanceCall": obj.get("maintenanceCall"),
            "maintenanceRequirement": obj.get("maintenanceRequirement"),
            "margin": obj.get("margin"),
            "marginEquity": obj.get("marginEquity"),
            "moneyMarketFund": obj.get("moneyMarketFund"),
            "mutualFundValue": obj.get("mutualFundValue"),
            "regTCall": obj.get("regTCall"),
            "shortMarginValue": obj.get("shortMarginValue"),
            "shortOptionMarketValue": obj.get("shortOptionMarketValue"),
            "shortStockValue": obj.get("shortStockValue"),
            "totalCash": obj.get("totalCash"),
            "isInCall": obj.get("isInCall"),
            "unsettledCash": obj.get("unsettledCash"),
            "pendingDeposits": obj.get("pendingDeposits"),
            "marginBalance": obj.get("marginBalance"),
            "shortBalance": obj.get("shortBalance"),
            "accountValue": obj.get("accountValue")
        })
        return _obj


