# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.asset_type import AssetType
from openapi_client.models.instruction import Instruction
from typing import Optional, Set
from typing_extensions import Self

class OrderLeg(BaseModel):
    """
    OrderLeg
    """ # noqa: E501
    ask_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="askPrice")
    bid_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="bidPrice")
    last_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="lastPrice")
    mark_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="markPrice")
    projected_commission: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="projectedCommission")
    quantity: Optional[Union[StrictFloat, StrictInt]] = None
    final_symbol: Optional[StrictStr] = Field(default=None, alias="finalSymbol")
    leg_id: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="legId")
    asset_type: Optional[AssetType] = Field(default=None, alias="assetType")
    instruction: Optional[Instruction] = None
    __properties: ClassVar[List[str]] = ["askPrice", "bidPrice", "lastPrice", "markPrice", "projectedCommission", "quantity", "finalSymbol", "legId", "assetType", "instruction"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrderLeg from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrderLeg from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "askPrice": obj.get("askPrice"),
            "bidPrice": obj.get("bidPrice"),
            "lastPrice": obj.get("lastPrice"),
            "markPrice": obj.get("markPrice"),
            "projectedCommission": obj.get("projectedCommission"),
            "quantity": obj.get("quantity"),
            "finalSymbol": obj.get("finalSymbol"),
            "legId": obj.get("legId"),
            "assetType": obj.get("assetType"),
            "instruction": obj.get("instruction")
        })
        return _obj


