# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OrderTypeRequest(str, Enum):
    """
    Same as orderType, but does not have UNKNOWN since this type is not allowed as an input
    """

    """
    allowed enum values
    """
    MARKET = 'MARKET'
    LIMIT = 'LIMIT'
    STOP = 'STOP'
    STOP_LIMIT = 'STOP_LIMIT'
    TRAILING_STOP = 'TRAILING_STOP'
    CABINET = 'CABINET'
    NON_MARKETABLE = 'NON_MARKETABLE'
    MARKET_ON_CLOSE = 'MARKET_ON_CLOSE'
    EXERCISE = 'EXERCISE'
    TRAILING_STOP_LIMIT = 'TRAILING_STOP_LIMIT'
    NET_DEBIT = 'NET_DEBIT'
    NET_CREDIT = 'NET_CREDIT'
    NET_ZERO = 'NET_ZERO'
    LIMIT_ON_CLOSE = 'LIMIT_ON_CLOSE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OrderTypeRequest from a JSON string"""
        return cls(json.loads(json_str))


