# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class StreamerInfo(BaseModel):
    """
    StreamerInfo
    """ # noqa: E501
    streamer_socket_url: Optional[StrictStr] = Field(default=None, alias="streamerSocketUrl")
    schwab_client_customer_id: Optional[StrictStr] = Field(default=None, alias="schwabClientCustomerId")
    schwab_client_correl_id: Optional[StrictStr] = Field(default=None, alias="schwabClientCorrelId")
    schwab_client_channel: Optional[StrictStr] = Field(default=None, alias="schwabClientChannel")
    schwab_client_function_id: Optional[StrictStr] = Field(default=None, alias="schwabClientFunctionId")
    __properties: ClassVar[List[str]] = ["streamerSocketUrl", "schwabClientCustomerId", "schwabClientCorrelId", "schwabClientChannel", "schwabClientFunctionId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StreamerInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StreamerInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "streamerSocketUrl": obj.get("streamerSocketUrl"),
            "schwabClientCustomerId": obj.get("schwabClientCustomerId"),
            "schwabClientCorrelId": obj.get("schwabClientCorrelId"),
            "schwabClientChannel": obj.get("schwabClientChannel"),
            "schwabClientFunctionId": obj.get("schwabClientFunctionId")
        })
        return _obj


