# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UserDetails(BaseModel):
    """
    UserDetails
    """ # noqa: E501
    cd_domain_id: Optional[StrictStr] = Field(default=None, alias="cdDomainId")
    login: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    user_id: Optional[StrictInt] = Field(default=None, alias="userId")
    system_user_name: Optional[StrictStr] = Field(default=None, alias="systemUserName")
    first_name: Optional[StrictStr] = Field(default=None, alias="firstName")
    last_name: Optional[StrictStr] = Field(default=None, alias="lastName")
    broker_rep_code: Optional[StrictStr] = Field(default=None, alias="brokerRepCode")
    __properties: ClassVar[List[str]] = ["cdDomainId", "login", "type", "userId", "systemUserName", "firstName", "lastName", "brokerRepCode"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ADVISOR_USER', 'BROKER_USER', 'CLIENT_USER', 'SYSTEM_USER', 'UNKNOWN']):
            raise ValueError("must be one of enum values ('ADVISOR_USER', 'BROKER_USER', 'CLIENT_USER', 'SYSTEM_USER', 'UNKNOWN')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cdDomainId": obj.get("cdDomainId"),
            "login": obj.get("login"),
            "type": obj.get("type"),
            "userId": obj.get("userId"),
            "systemUserName": obj.get("systemUserName"),
            "firstName": obj.get("firstName"),
            "lastName": obj.get("lastName"),
            "brokerRepCode": obj.get("brokerRepCode")
        })
        return _obj


