# coding: utf-8

"""
    Trader API - Account Access and User Preferences

    Schwab Trader API access to Account, Order entry and User Preferences

    The version of the OpenAPI document: 1.0.0
    Contact: TraderAPI@Schwab.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.offer import Offer
from openapi_client.models.streamer_info import StreamerInfo
from openapi_client.models.user_preference_account import UserPreferenceAccount
from typing import Optional, Set
from typing_extensions import Self

class UserPreference(BaseModel):
    """
    UserPreference
    """ # noqa: E501
    accounts: Optional[List[UserPreferenceAccount]] = None
    streamer_info: Optional[List[StreamerInfo]] = Field(default=None, alias="streamerInfo")
    offers: Optional[List[Offer]] = None
    __properties: ClassVar[List[str]] = ["accounts", "streamerInfo", "offers"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserPreference from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in accounts (list)
        _items = []
        if self.accounts:
            for _item_accounts in self.accounts:
                if _item_accounts:
                    _items.append(_item_accounts.to_dict())
            _dict['accounts'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in streamer_info (list)
        _items = []
        if self.streamer_info:
            for _item_streamer_info in self.streamer_info:
                if _item_streamer_info:
                    _items.append(_item_streamer_info.to_dict())
            _dict['streamerInfo'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in offers (list)
        _items = []
        if self.offers:
            for _item_offers in self.offers:
                if _item_offers:
                    _items.append(_item_offers.to_dict())
            _dict['offers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserPreference from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accounts": [UserPreferenceAccount.from_dict(_item) for _item in obj["accounts"]] if obj.get("accounts") is not None else None,
            "streamerInfo": [StreamerInfo.from_dict(_item) for _item in obj["streamerInfo"]] if obj.get("streamerInfo") is not None else None,
            "offers": [Offer.from_dict(_item) for _item in obj["offers"]] if obj.get("offers") is not None else None
        })
        return _obj


